WIDTH, HEIGHT = 900, 600
WINDOW_TITLE = "Survival Game"
FPS = 60

START_POS = (420, 280)
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 40
PLAYER_SPEED = 5

HOME_AREA_OFFSET = (30, 30)
HOME_AREA_SIZE = (110, 110)

TREE_SIZE = (50, 70)
STONE_SIZE = (50, 40)
INITIAL_TREE_COUNT = 5
INITIAL_STONE_COUNT = 5

TREE_RESPAWN_SECONDS = 6.0
STONE_RESPAWN_SECONDS = 7.0

CUT_TIME_SECONDS = 5.0
CUT_TIME_WITH_AXE = 3.0
MINE_TIME_SECONDS = 8.0

RARE_DROP_CHANCE = 0.25

AXE_COST_WOOD = 1
PICK_COST_WOOD = 2
PICK_COST_STONE = 0

QUEST_TEXT = 'Quest: Build a house and get "2 rare stones".'
