WIDTH, HEIGHT = 900, 600
WINDOW_TITLE = "Survival Game"
FPS = 60
LANDSCAPE_SEED = "2151901553968352745"

# World-space size (bigger than the visible screen for exploration).
WORLD_WIDTH, WORLD_HEIGHT = 6200, 4000

START_POS = (WORLD_WIDTH // 2, WORLD_HEIGHT // 2)
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 40
PLAYER_SPEED = 5

HOME_AREA_OFFSET = (30, 30)
HOME_AREA_SIZE = (110, 110)
HOUSE_SIZE = (70, 70)
FURNACE_SIZE = (54, 54)

TREE_SIZE = (50, 70)
STONE_SIZE = (50, 40)
ANIMAL_SIZE = (48, 34)
INITIAL_TREE_COUNT = 8
INITIAL_STONE_COUNT = 8
INITIAL_ANIMAL_COUNT = 12
ANIMAL_SPEED = 38.0
ANIMAL_WANDER_SECONDS = (1.2, 3.4)

TREE_RESPAWN_SECONDS = 6.0
STONE_RESPAWN_SECONDS = 7.0

CUT_TIME_SECONDS = 5.0
CUT_TIME_WITH_AXE = 3.0
MINE_TIME_SECONDS = 8.0
SMELTED_PICK_MINE_TIME_SECONDS = 4.0

RARE_DROP_CHANCE = 0.25

AXE_COST_WOOD = 1
PICK_COST_WOOD = 2
PICK_COST_STONE = 0
FURNACE_COST_STONE = 8
SMELTED_PICK_COST_WOOD = 2
SMELTED_PICK_COST_SMELTED_STONE = 1

QUEST_TEXT = 'Quest: Build a house and get "2 rare stones".'
NEW_QUEST_TEXT = 'New Quest: Make "2 fire" and return home.'
QUEST_COUNT = 5
